"""Stable public identifiers for UE Chain Prep schema 3.x."""

from __future__ import annotations

from enum import Enum


ADDON_ID = "ue_chain_prep"
ADDON_VERSION = "0.1.3"
SCHEMA_VERSION = "3.1.0"
ALGORITHM_VERSION = "uecp-physics-graph-v3-interaction-hardening"


class StableStringEnum(str, Enum):
    """String enum whose serialized value is its stable public identifier."""


class ScopeMode(StableStringEnum):
    SELECTED_BONES = "SELECTED_BONES"
    SELECTED_ROOTS_AND_DESCENDANTS = "SELECTED_ROOTS_AND_DESCENDANTS"
    ACTIVE_BONE_COLLECTION = "ACTIVE_BONE_COLLECTION"


class MeshScope(StableStringEnum):
    ACTIVE_ASSOCIATED_MESH = "ACTIVE_ASSOCIATED_MESH"
    CHECKED_ASSOCIATED_MESHES = "CHECKED_ASSOCIATED_MESHES"
    ALL_ASSOCIATED_MESHES = "ALL_ASSOCIATED_MESHES"


class ValidationToleranceMode(StableStringEnum):
    AUTO_PRODUCTION = "AUTO_PRODUCTION"
    STRICT_TEST = "STRICT_TEST"
    CUSTOM = "CUSTOM"


class PhysicsProfile(StableStringEnum):
    BONEX_ROTATION_CHAIN = "BONEX_ROTATION_CHAIN"
    BONEX_TRANSLATION_ALLOWED = "BONEX_TRANSLATION_ALLOWED"
    WIGGLE2_ROTATION_CHAIN = "WIGGLE2_ROTATION_CHAIN"
    WIGGLE2_STRETCH_CHAIN = "WIGGLE2_STRETCH_CHAIN"
    GEOMETRY_ONLY = "GEOMETRY_ONLY"


class BranchResolutionMode(StableStringEnum):
    AUTO_MAIN_PATH = "AUTO_MAIN_PATH"
    LONGEST_PATH_ONLY = "LONGEST_PATH_ONLY"
    DIRECTION_CONTINUITY = "DIRECTION_CONTINUITY"
    MANUAL_ONLY = "MANUAL_ONLY"
    KEEP_ORIGINAL = "KEEP_ORIGINAL"


class TerminalMode(StableStringEnum):
    AUTO_HYBRID = "AUTO_HYBRID"
    UNIQUE_CHILD_ONLY = "UNIQUE_CHILD_ONLY"
    IMPORTED_FORWARD_AXIS_ONLY = "IMPORTED_FORWARD_AXIS_ONLY"
    WEIGHT_CLOUD_ONLY = "WEIGHT_CLOUD_ONLY"
    PARENT_EXTRAPOLATION_ONLY = "PARENT_EXTRAPOLATION_ONLY"
    ORIGINAL_AXIS_ONLY = "ORIGINAL_AXIS_ONLY"
    MANUAL_ONLY = "MANUAL_ONLY"


class TerminalSource(StableStringEnum):
    MANUAL_OVERRIDE = "MANUAL_OVERRIDE"
    UNIQUE_DIRECT_CHILD_HEAD = "UNIQUE_DIRECT_CHILD_HEAD"
    IMPORTED_FORWARD_AXIS_DUMMY = "IMPORTED_FORWARD_AXIS_DUMMY"
    WEIGHT_CLOUD_LINEAR = "WEIGHT_CLOUD_LINEAR"
    WEIGHT_CLOUD_PLANAR_BLEND = "WEIGHT_CLOUD_PLANAR_BLEND"
    PARENT_CHAIN_EXTRAPOLATION = "PARENT_CHAIN_EXTRAPOLATION"
    ORIGINAL_LOCAL_Y = "ORIGINAL_LOCAL_Y"
    HYBRID_CANDIDATE_SCORE = "HYBRID_CANDIDATE_SCORE"
    UNRESOLVED = "UNRESOLVED"


class TerminalResolutionClass(StableStringEnum):
    AUTO_CONFIDENT = "AUTO_CONFIDENT"
    AUTO_SAFE_FALLBACK = "AUTO_SAFE_FALLBACK"
    MANUAL = "MANUAL"
    UNRESOLVED = "UNRESOLVED"


class TerminalCandidateKind(StableStringEnum):
    MANUAL = "MANUAL"
    DIRECT_CHILD = "DIRECT_CHILD"
    IMPORTED_AXIS = "IMPORTED_AXIS"
    WEIGHT_PRINCIPAL_AXIS = "WEIGHT_PRINCIPAL_AXIS"
    WEIGHT_CENTROID = "WEIGHT_CENTROID"
    WEIGHT_PLANAR_BLEND = "WEIGHT_PLANAR_BLEND"
    PARENT_TANGENT = "PARENT_TANGENT"
    ORIGINAL_DISPLAY_AXIS = "ORIGINAL_DISPLAY_AXIS"


class BoneForwardAxis(StableStringEnum):
    AUTO = "AUTO"
    X_POSITIVE = "X_POSITIVE"
    X_NEGATIVE = "X_NEGATIVE"
    Y_POSITIVE = "Y_POSITIVE"
    Y_NEGATIVE = "Y_NEGATIVE"
    Z_POSITIVE = "Z_POSITIVE"
    Z_NEGATIVE = "Z_NEGATIVE"


class TipLengthMode(StableStringEnum):
    AUTO_EVIDENCE = "AUTO_EVIDENCE"
    WEIGHT_PERCENTILE = "WEIGHT_PERCENTILE"
    PREVIOUS_SEGMENT = "PREVIOUS_SEGMENT"
    CHAIN_MEDIAN = "CHAIN_MEDIAN"
    ABSOLUTE = "ABSOLUTE"


class PhysicsNodeKind(StableStringEnum):
    REAL_BONE = "REAL_BONE"
    VIRTUAL_TIP = "VIRTUAL_TIP"


class PhysicsEdgeKind(StableStringEnum):
    HIERARCHY_SEGMENT = "HIERARCHY_SEGMENT"
    VIRTUAL_TIP_SEGMENT = "VIRTUAL_TIP_SEGMENT"


class RollMode(StableStringEnum):
    MINIMAL_TWIST = "MINIMAL_TWIST"
    PARALLEL_TRANSPORT = "PARALLEL_TRANSPORT"
    RADIAL_REFERENCE = "RADIAL_REFERENCE"
    KEEP_NUMERIC_ROLL = "KEEP_NUMERIC_ROLL"


class RadialReferenceMode(StableStringEnum):
    ARMATURE_ORIGIN = "ARMATURE_ORIGIN"
    CURSOR = "CURSOR"
    OBJECT = "OBJECT"
    BONE_HEAD = "BONE_HEAD"


class ExclusivityMode(StableStringEnum):
    NONE = "NONE"
    CHAIN_NORMALIZED = "CHAIN_NORMALIZED"
    SELECTED_SET_NORMALIZED = "SELECTED_SET_NORMALIZED"


class PlanState(StableStringEnum):
    IDLE = "IDLE"
    ANALYZED = "ANALYZED"
    STALE = "STALE"
    APPLYING = "APPLYING"
    APPLIED = "APPLIED"
    VALIDATION_FAILED = "VALIDATION_FAILED"
    RESTORABLE = "RESTORABLE"
    RESTORED = "RESTORED"
    ERROR = "ERROR"


class PlanAvailability(StableStringEnum):
    NONE = "NONE"
    AVAILABLE = "AVAILABLE"
    MISSING = "MISSING"


class WorkflowStage(StableStringEnum):
    NO_CONTEXT = "NO_CONTEXT"
    READY_TO_ANALYZE = "READY_TO_ANALYZE"
    ANALYZING = "ANALYZING"
    READY_TO_APPLY = "READY_TO_APPLY"
    NEEDS_ATTENTION = "NEEDS_ATTENTION"
    BLOCKED = "BLOCKED"
    STALE_SETTINGS = "STALE_SETTINGS"
    STALE_SELECTION = "STALE_SELECTION"
    PLAN_LOST = "PLAN_LOST"
    APPLYING = "APPLYING"
    APPLIED = "APPLIED"
    ROLLBACK_FAILED = "ROLLBACK_FAILED"
    ERROR = "ERROR"


class ActionAvailability(StableStringEnum):
    ENABLED = "ENABLED"
    DISABLED = "DISABLED"


class IssueSeverity(StableStringEnum):
    INFO = "INFO"
    WARNING = "WARNING"
    BLOCKER = "BLOCKER"


class OverrideMode(StableStringEnum):
    NONE = "NONE"
    CURSOR_POSITION = "CURSOR_POSITION"
    REFERENCE_OBJECT = "REFERENCE_OBJECT"
    EXPLICIT_DIRECTION_LENGTH = "EXPLICIT_DIRECTION_LENGTH"
    MESH_VERTEX = "MESH_VERTEX"


OPERATOR_IDS = {
    "analyze": "uecp.analyze",
    "check_and_preview": "uecp.check_and_preview",
    "apply": "uecp.apply",
    "validate": "uecp.validate",
    "preview_toggle": "uecp.preview_toggle",
    "restore_snapshot": "uecp.restore_snapshot",
    "export_report": "uecp.export_report",
    "export_conversion": "uecp.export_conversion",
    "clear_runtime": "uecp.clear_runtime",
    "locate_issue": "uecp.locate_issue",
    "load_details": "uecp.load_details",
}

CANDIDATE_SCORING_PROFILE = (
    ("mesh_support", 0.40),
    ("chain_continuity", 0.25),
    ("cloud_shape_suitability", 0.15),
    ("imported_axis_prior", 0.10),
    ("length_plausibility", 0.10),
)

ERROR_CODES = frozenset(
    {
        "UECP_NO_ACTIVE_ARMATURE", "UECP_EMPTY_SELECTION", "UECP_LINKED_ARMATURE",
        "UECP_SHARED_ARMATURE_DATA", "UECP_UNSUPPORTED_CONTEXT",
        "UECP_NON_INVERTIBLE_TRANSFORM", "UECP_NEGATIVE_OBJECT_TRANSFORM",
        "UECP_NON_UNIFORM_OBJECT_SCALE", "UECP_NON_IDENTITY_POSE",
        "UECP_RELATED_ACTION", "UECP_RELATED_NLA", "UECP_RELATED_DRIVER",
        "UECP_RELATED_CONSTRAINT", "UECP_BONE_PARENTED_OBJECT",
        "UECP_EXTERNAL_CONNECTED_CHILD", "UECP_BRANCH_AMBIGUOUS",
        "UECP_COINCIDENT_HELPER", "UECP_ZERO_LENGTH_PROPOSAL",
        "UECP_NO_ASSOCIATED_MESH", "UECP_NO_WEIGHT_GROUP",
        "UECP_INSUFFICIENT_WEIGHT_CLOUD", "UECP_DISCONNECTED_WEIGHT_ISLANDS",
        "UECP_LOW_WEIGHT_CONFIDENCE", "UECP_IMPORTED_FORWARD_AXIS_UNAVAILABLE",
        "UECP_FORWARD_AXIS_AMBIGUOUS", "UECP_TERMINAL_CANDIDATE_AMBIGUOUS",
        "UECP_TERMINAL_CANDIDATE_SCORE_TOO_LOW", "UECP_VIRTUAL_TIP_INVALID",
        "UECP_PHYSICS_GRAPH_INVALID", "UECP_GRAPH_PROJECTION_MISMATCH",
        "UECP_LONG_SEGMENT_SAMPLING_HINT", "UECP_WEIGHT_DIRECTION_CONFLICT",
        "UECP_ENVELOPE_DEFORMATION", "UECP_ENVELOPE_MULTIPLY",
        "UECP_BBONE_UNSUPPORTED", "UECP_AMBIGUOUS_ARMATURE_MODIFIER",
        "UECP_TOPOLOGY_MODIFIER_BEFORE_ARMATURE", "UECP_STATE_CHANGED_AFTER_ANALYZE",
        "UECP_SETTINGS_CHANGED_AFTER_ANALYZE", "UECP_WEIGHT_DIGEST_CHANGED",
        "UECP_BASE_MESH_CHANGED", "UECP_MODIFIER_DIGEST_CHANGED",
        "UECP_NEUTRAL_MESH_CHANGED", "UECP_NON_TARGET_BONE_CHANGED",
        "UECP_ROLL_FALLBACK_USED", "UECP_SNAPSHOT_WRITE_FAILED",
        "UECP_ROLLBACK_FAILED", "UECP_RESTORE_CONFLICT",
        "UECP_SCHEMA_VERSION_UNSUPPORTED", "UECP_INTERNAL_ERROR",
        "UECP_TERMINAL_SAFE_FALLBACK_USED", "UECP_TERMINAL_PARENT_UNAVAILABLE",
        "UECP_TERMINAL_FALLBACK_INELIGIBLE", "UECP_TERMINAL_LENGTH_EVIDENCE_INVALID",
        "UECP_BRANCH_MEDIUM_CONFIDENCE", "UECP_LEGACY_OVERRIDE_UNSCOPED",
        "UECP_UNRECORDED_BONE_MUTATION", "UECP_MUTATION_WITHOUT_PROPOSAL",
        "UECP_EXPORT_PLAN_MISSING", "UECP_EXPORT_PLAN_STALE",
        "UECP_EXPORT_APPLY_NOT_SUCCESSFUL", "UECP_EXPORT_SNAPSHOT_MISSING",
        "UECP_EXPORT_SNAPSHOT_PLAN_MISMATCH", "UECP_EXPORT_NO_ACTUAL_MUTATION",
        "UECP_EXPORT_POST_VALIDATION_FAILED", "UECP_EXPORT_TOPOLOGY_LEDGER_MISSING",
        "UECP_EXPORT_TOPOLOGY_LEDGER_INCOMPLETE", "UECP_EXPORT_MUTATION_LEDGER_MISMATCH",
        "UECP_EXPORT_UNRESOLVED_BLOCKER", "UECP_EXPORT_SOURCE_FILE_MISSING",
        "UECP_EXPORT_SOURCE_OVERWRITE_FORBIDDEN", "UECP_EXPORT_SOURCE_FILE_CHANGED",
        "UECP_REOPEN_VALIDATION_FAILED", "UECP_REOPEN_MANIFEST_MISSING",
        "UECP_REOPEN_SNAPSHOT_MISSING", "UECP_REOPEN_SNAPSHOT_NOT_APPLIED",
        "UECP_REOPEN_MUTATION_LEDGER_MISMATCH", "UECP_REOPEN_ARMATURE_MISSING",
        "UECP_REOPEN_BONE_MISSING", "UECP_REOPEN_REST_GEOMETRY_MISMATCH",
        "UECP_REOPEN_CONNECT_MISMATCH", "UECP_REOPEN_BRANCH_MAIN_PATH_MISMATCH",
        "UECP_REOPEN_BRANCH_SIDE_CONNECT_MISMATCH", "UECP_REOPEN_LINEAR_CONTINUITY_MISMATCH",
        "UECP_REOPEN_PACKED_IMAGE_COUNT_MISMATCH",
    }
)
