"""Stable public identifiers for UE Chain Prep schema 3.x."""

from __future__ import annotations

from enum import Enum


ADDON_ID = "ue_chain_prep"
ADDON_VERSION = "0.1.0"
SCHEMA_VERSION = "3.0.0"
ALGORITHM_VERSION = "uecp-physics-graph-v1"


class StableStringEnum(str, Enum):
    """String enum whose serialized value is its stable public identifier."""


class ScopeMode(StableStringEnum):
    SELECTED_BONES = "SELECTED_BONES"
    SELECTED_ROOTS_AND_DESCENDANTS = "SELECTED_ROOTS_AND_DESCENDANTS"
    ACTIVE_BONE_COLLECTION = "ACTIVE_BONE_COLLECTION"


class MeshScope(StableStringEnum):
    ACTIVE_ASSOCIATED_MESH = "ACTIVE_ASSOCIATED_MESH"
    CHECKED_ASSOCIATED_MESHES = "CHECKED_ASSOCIATED_MESHES"
    ALL_ASSOCIATED_MESHES = "ALL_ASSOCIATED_MESHES"


class PhysicsProfile(StableStringEnum):
    BONEX_ROTATION_CHAIN = "BONEX_ROTATION_CHAIN"
    BONEX_TRANSLATION_ALLOWED = "BONEX_TRANSLATION_ALLOWED"
    WIGGLE2_ROTATION_CHAIN = "WIGGLE2_ROTATION_CHAIN"
    WIGGLE2_STRETCH_CHAIN = "WIGGLE2_STRETCH_CHAIN"
    GEOMETRY_ONLY = "GEOMETRY_ONLY"


class TerminalMode(StableStringEnum):
    AUTO_HYBRID = "AUTO_HYBRID"
    UNIQUE_CHILD_ONLY = "UNIQUE_CHILD_ONLY"
    IMPORTED_FORWARD_AXIS_ONLY = "IMPORTED_FORWARD_AXIS_ONLY"
    WEIGHT_CLOUD_ONLY = "WEIGHT_CLOUD_ONLY"
    PARENT_EXTRAPOLATION_ONLY = "PARENT_EXTRAPOLATION_ONLY"
    ORIGINAL_AXIS_ONLY = "ORIGINAL_AXIS_ONLY"
    MANUAL_ONLY = "MANUAL_ONLY"


class TerminalSource(StableStringEnum):
    MANUAL_OVERRIDE = "MANUAL_OVERRIDE"
    UNIQUE_DIRECT_CHILD_HEAD = "UNIQUE_DIRECT_CHILD_HEAD"
    IMPORTED_FORWARD_AXIS_DUMMY = "IMPORTED_FORWARD_AXIS_DUMMY"
    WEIGHT_CLOUD_LINEAR = "WEIGHT_CLOUD_LINEAR"
    WEIGHT_CLOUD_PLANAR_BLEND = "WEIGHT_CLOUD_PLANAR_BLEND"
    PARENT_CHAIN_EXTRAPOLATION = "PARENT_CHAIN_EXTRAPOLATION"
    ORIGINAL_LOCAL_Y = "ORIGINAL_LOCAL_Y"
    HYBRID_CANDIDATE_SCORE = "HYBRID_CANDIDATE_SCORE"
    UNRESOLVED = "UNRESOLVED"


class TerminalCandidateKind(StableStringEnum):
    MANUAL = "MANUAL"
    DIRECT_CHILD = "DIRECT_CHILD"
    IMPORTED_AXIS = "IMPORTED_AXIS"
    WEIGHT_PRINCIPAL_AXIS = "WEIGHT_PRINCIPAL_AXIS"
    WEIGHT_CENTROID = "WEIGHT_CENTROID"
    WEIGHT_PLANAR_BLEND = "WEIGHT_PLANAR_BLEND"
    PARENT_TANGENT = "PARENT_TANGENT"
    ORIGINAL_DISPLAY_AXIS = "ORIGINAL_DISPLAY_AXIS"


class BoneForwardAxis(StableStringEnum):
    AUTO = "AUTO"
    X_POSITIVE = "X_POSITIVE"
    X_NEGATIVE = "X_NEGATIVE"
    Y_POSITIVE = "Y_POSITIVE"
    Y_NEGATIVE = "Y_NEGATIVE"
    Z_POSITIVE = "Z_POSITIVE"
    Z_NEGATIVE = "Z_NEGATIVE"


class TipLengthMode(StableStringEnum):
    AUTO_EVIDENCE = "AUTO_EVIDENCE"
    WEIGHT_PERCENTILE = "WEIGHT_PERCENTILE"
    PREVIOUS_SEGMENT = "PREVIOUS_SEGMENT"
    CHAIN_MEDIAN = "CHAIN_MEDIAN"
    ABSOLUTE = "ABSOLUTE"


class PhysicsNodeKind(StableStringEnum):
    REAL_BONE = "REAL_BONE"
    VIRTUAL_TIP = "VIRTUAL_TIP"


class PhysicsEdgeKind(StableStringEnum):
    HIERARCHY_SEGMENT = "HIERARCHY_SEGMENT"
    VIRTUAL_TIP_SEGMENT = "VIRTUAL_TIP_SEGMENT"


class RollMode(StableStringEnum):
    MINIMAL_TWIST = "MINIMAL_TWIST"
    PARALLEL_TRANSPORT = "PARALLEL_TRANSPORT"
    RADIAL_REFERENCE = "RADIAL_REFERENCE"
    KEEP_NUMERIC_ROLL = "KEEP_NUMERIC_ROLL"


class RadialReferenceMode(StableStringEnum):
    ARMATURE_ORIGIN = "ARMATURE_ORIGIN"
    CURSOR = "CURSOR"
    OBJECT = "OBJECT"
    BONE_HEAD = "BONE_HEAD"


class ExclusivityMode(StableStringEnum):
    NONE = "NONE"
    CHAIN_NORMALIZED = "CHAIN_NORMALIZED"
    SELECTED_SET_NORMALIZED = "SELECTED_SET_NORMALIZED"


class PlanState(StableStringEnum):
    IDLE = "IDLE"
    ANALYZED = "ANALYZED"
    STALE = "STALE"
    APPLYING = "APPLYING"
    APPLIED = "APPLIED"
    VALIDATION_FAILED = "VALIDATION_FAILED"
    RESTORABLE = "RESTORABLE"
    RESTORED = "RESTORED"
    ERROR = "ERROR"


class IssueSeverity(StableStringEnum):
    INFO = "INFO"
    WARNING = "WARNING"
    BLOCKER = "BLOCKER"


class OverrideMode(StableStringEnum):
    NONE = "NONE"
    CURSOR_POSITION = "CURSOR_POSITION"
    REFERENCE_OBJECT = "REFERENCE_OBJECT"
    EXPLICIT_DIRECTION_LENGTH = "EXPLICIT_DIRECTION_LENGTH"
    MESH_VERTEX = "MESH_VERTEX"


OPERATOR_IDS = {
    "analyze": "uecp.analyze",
    "apply": "uecp.apply",
    "validate": "uecp.validate",
    "preview_toggle": "uecp.preview_toggle",
    "restore_snapshot": "uecp.restore_snapshot",
    "export_report": "uecp.export_report",
    "clear_runtime": "uecp.clear_runtime",
}

CANDIDATE_SCORING_PROFILE = (
    ("mesh_support", 0.40),
    ("chain_continuity", 0.25),
    ("cloud_shape_suitability", 0.15),
    ("imported_axis_prior", 0.10),
    ("length_plausibility", 0.10),
)

ERROR_CODES = frozenset(
    {
        "UECP_NO_ACTIVE_ARMATURE", "UECP_EMPTY_SELECTION", "UECP_LINKED_ARMATURE",
        "UECP_SHARED_ARMATURE_DATA", "UECP_UNSUPPORTED_CONTEXT",
        "UECP_NON_INVERTIBLE_TRANSFORM", "UECP_NEGATIVE_OBJECT_TRANSFORM",
        "UECP_NON_UNIFORM_OBJECT_SCALE", "UECP_NON_IDENTITY_POSE",
        "UECP_RELATED_ACTION", "UECP_RELATED_NLA", "UECP_RELATED_DRIVER",
        "UECP_RELATED_CONSTRAINT", "UECP_BONE_PARENTED_OBJECT",
        "UECP_EXTERNAL_CONNECTED_CHILD", "UECP_BRANCH_AMBIGUOUS",
        "UECP_COINCIDENT_HELPER", "UECP_ZERO_LENGTH_PROPOSAL",
        "UECP_NO_ASSOCIATED_MESH", "UECP_NO_WEIGHT_GROUP",
        "UECP_INSUFFICIENT_WEIGHT_CLOUD", "UECP_DISCONNECTED_WEIGHT_ISLANDS",
        "UECP_LOW_WEIGHT_CONFIDENCE", "UECP_IMPORTED_FORWARD_AXIS_UNAVAILABLE",
        "UECP_FORWARD_AXIS_AMBIGUOUS", "UECP_TERMINAL_CANDIDATE_AMBIGUOUS",
        "UECP_TERMINAL_CANDIDATE_SCORE_TOO_LOW", "UECP_VIRTUAL_TIP_INVALID",
        "UECP_PHYSICS_GRAPH_INVALID", "UECP_GRAPH_PROJECTION_MISMATCH",
        "UECP_LONG_SEGMENT_SAMPLING_HINT", "UECP_WEIGHT_DIRECTION_CONFLICT",
        "UECP_ENVELOPE_DEFORMATION", "UECP_ENVELOPE_MULTIPLY",
        "UECP_BBONE_UNSUPPORTED", "UECP_AMBIGUOUS_ARMATURE_MODIFIER",
        "UECP_TOPOLOGY_MODIFIER_BEFORE_ARMATURE", "UECP_STATE_CHANGED_AFTER_ANALYZE",
        "UECP_SETTINGS_CHANGED_AFTER_ANALYZE", "UECP_WEIGHT_DIGEST_CHANGED",
        "UECP_BASE_MESH_CHANGED", "UECP_MODIFIER_DIGEST_CHANGED",
        "UECP_NEUTRAL_MESH_CHANGED", "UECP_NON_TARGET_BONE_CHANGED",
        "UECP_ROLL_FALLBACK_USED", "UECP_SNAPSHOT_WRITE_FAILED",
        "UECP_ROLLBACK_FAILED", "UECP_RESTORE_CONFLICT",
        "UECP_SCHEMA_VERSION_UNSUPPORTED", "UECP_INTERNAL_ERROR",
    }
)
