"""Stable public identifiers for BoneWeaver schema 4.x."""

from __future__ import annotations

from enum import Enum


ADDON_ID = "boneweaver"
ADDON_VERSION = "0.3.0"
SCHEMA_VERSION = "4.0.0"
ALGORITHM_VERSION = "boneweaver-physics-graph-v4-tip-helper-branch-island-visual-cleanup"
QUICK_REORIENT_ALGORITHM_VERSION = "boneweaver-quick-reorient-v1.0.0"
QUICK_REORIENT_SCHEMA_VERSION = "1.0.0"


class StableStringEnum(str, Enum):
    """String enum whose serialized value is its stable public identifier."""


class ScopeMode(StableStringEnum):
    SELECTED_BONES = "SELECTED_BONES"
    SELECTED_ROOTS_AND_DESCENDANTS = "SELECTED_ROOTS_AND_DESCENDANTS"
    ACTIVE_BONE_COLLECTION = "ACTIVE_BONE_COLLECTION"


class MeshScope(StableStringEnum):
    ACTIVE_ASSOCIATED_MESH = "ACTIVE_ASSOCIATED_MESH"
    CHECKED_ASSOCIATED_MESHES = "CHECKED_ASSOCIATED_MESHES"
    ALL_ASSOCIATED_MESHES = "ALL_ASSOCIATED_MESHES"


class ValidationToleranceMode(StableStringEnum):
    AUTO_PRODUCTION = "AUTO_PRODUCTION"
    STRICT_TEST = "STRICT_TEST"
    CUSTOM = "CUSTOM"


class PhysicsProfile(StableStringEnum):
    BONEX_ROTATION_CHAIN = "BONEX_ROTATION_CHAIN"
    BONEX_TRANSLATION_ALLOWED = "BONEX_TRANSLATION_ALLOWED"
    WIGGLE2_ROTATION_CHAIN = "WIGGLE2_ROTATION_CHAIN"
    WIGGLE2_STRETCH_CHAIN = "WIGGLE2_STRETCH_CHAIN"
    GEOMETRY_ONLY = "GEOMETRY_ONLY"
    VISUAL_CHAIN_CLEANUP = "VISUAL_CHAIN_CLEANUP"


class BranchResolutionMode(StableStringEnum):
    AUTO_MAIN_PATH = "AUTO_MAIN_PATH"
    LONGEST_PATH_ONLY = "LONGEST_PATH_ONLY"
    DIRECTION_CONTINUITY = "DIRECTION_CONTINUITY"
    MANUAL_ONLY = "MANUAL_ONLY"
    KEEP_ORIGINAL = "KEEP_ORIGINAL"


class WeightIslandPolicy(StableStringEnum):
    DOMINANT_COMPONENT = "DOMINANT_COMPONENT"
    REQUIRE_SINGLE_COMPONENT = "REQUIRE_SINGLE_COMPONENT"
    ALL_COMPATIBLE_COMPONENTS = "ALL_COMPATIBLE_COMPONENTS"


class TerminalMode(StableStringEnum):
    AUTO_HYBRID = "AUTO_HYBRID"
    UNIQUE_CHILD_ONLY = "UNIQUE_CHILD_ONLY"
    IMPORTED_FORWARD_AXIS_ONLY = "IMPORTED_FORWARD_AXIS_ONLY"
    WEIGHT_CLOUD_ONLY = "WEIGHT_CLOUD_ONLY"
    PARENT_EXTRAPOLATION_ONLY = "PARENT_EXTRAPOLATION_ONLY"
    ORIGINAL_AXIS_ONLY = "ORIGINAL_AXIS_ONLY"
    MANUAL_ONLY = "MANUAL_ONLY"


class TerminalSource(StableStringEnum):
    MANUAL_OVERRIDE = "MANUAL_OVERRIDE"
    EXISTING_TIP_HELPER_HEAD = "EXISTING_TIP_HELPER_HEAD"
    UNIQUE_DIRECT_CHILD_HEAD = "UNIQUE_DIRECT_CHILD_HEAD"
    IMPORTED_FORWARD_AXIS_DUMMY = "IMPORTED_FORWARD_AXIS_DUMMY"
    WEIGHT_CLOUD_LINEAR = "WEIGHT_CLOUD_LINEAR"
    WEIGHT_CLOUD_PLANAR_BLEND = "WEIGHT_CLOUD_PLANAR_BLEND"
    PARENT_CHAIN_EXTRAPOLATION = "PARENT_CHAIN_EXTRAPOLATION"
    ORIGINAL_LOCAL_Y = "ORIGINAL_LOCAL_Y"
    HYBRID_CANDIDATE_SCORE = "HYBRID_CANDIDATE_SCORE"
    UNRESOLVED = "UNRESOLVED"


class BoneSemanticRole(StableStringEnum):
    DEFORM_SEGMENT = "DEFORM_SEGMENT"
    EXISTING_TIP_HELPER = "EXISTING_TIP_HELPER"
    CONTROL_EFFECTOR = "CONTROL_EFFECTOR"
    TWIST_HELPER = "TWIST_HELPER"
    SOCKET_HELPER = "SOCKET_HELPER"
    UNKNOWN_HELPER = "UNKNOWN_HELPER"


class TipHelperUsage(StableStringEnum):
    REFERENCE_ONLY = "REFERENCE_ONLY"
    INCLUDE_AS_PHYSICS_TERMINAL = "INCLUDE_AS_PHYSICS_TERMINAL"


class TerminalResolutionClass(StableStringEnum):
    AUTO_CONFIDENT = "AUTO_CONFIDENT"
    AUTO_SAFE_FALLBACK = "AUTO_SAFE_FALLBACK"
    MANUAL = "MANUAL"
    UNRESOLVED = "UNRESOLVED"


class TerminalCandidateKind(StableStringEnum):
    MANUAL = "MANUAL"
    DIRECT_CHILD = "DIRECT_CHILD"
    IMPORTED_AXIS = "IMPORTED_AXIS"
    WEIGHT_PRINCIPAL_AXIS = "WEIGHT_PRINCIPAL_AXIS"
    WEIGHT_CENTROID = "WEIGHT_CENTROID"
    WEIGHT_PLANAR_BLEND = "WEIGHT_PLANAR_BLEND"
    PARENT_TANGENT = "PARENT_TANGENT"
    ORIGINAL_DISPLAY_AXIS = "ORIGINAL_DISPLAY_AXIS"


class BoneForwardAxis(StableStringEnum):
    AUTO = "AUTO"
    X_POSITIVE = "X_POSITIVE"
    X_NEGATIVE = "X_NEGATIVE"
    Y_POSITIVE = "Y_POSITIVE"
    Y_NEGATIVE = "Y_NEGATIVE"
    Z_POSITIVE = "Z_POSITIVE"
    Z_NEGATIVE = "Z_NEGATIVE"


class TipLengthMode(StableStringEnum):
    AUTO_EVIDENCE = "AUTO_EVIDENCE"
    WEIGHT_PERCENTILE = "WEIGHT_PERCENTILE"
    PREVIOUS_SEGMENT = "PREVIOUS_SEGMENT"
    CHAIN_MEDIAN = "CHAIN_MEDIAN"
    ABSOLUTE = "ABSOLUTE"


class PhysicsNodeKind(StableStringEnum):
    REAL_BONE = "REAL_BONE"
    VIRTUAL_TIP = "VIRTUAL_TIP"


class PhysicsEdgeKind(StableStringEnum):
    HIERARCHY_SEGMENT = "HIERARCHY_SEGMENT"
    VIRTUAL_TIP_SEGMENT = "VIRTUAL_TIP_SEGMENT"


class RollMode(StableStringEnum):
    MINIMAL_TWIST = "MINIMAL_TWIST"
    PARALLEL_TRANSPORT = "PARALLEL_TRANSPORT"
    RADIAL_REFERENCE = "RADIAL_REFERENCE"
    KEEP_NUMERIC_ROLL = "KEEP_NUMERIC_ROLL"


class RadialReferenceMode(StableStringEnum):
    ARMATURE_ORIGIN = "ARMATURE_ORIGIN"
    CURSOR = "CURSOR"
    OBJECT = "OBJECT"
    BONE_HEAD = "BONE_HEAD"


class ExclusivityMode(StableStringEnum):
    NONE = "NONE"
    CHAIN_NORMALIZED = "CHAIN_NORMALIZED"
    SELECTED_SET_NORMALIZED = "SELECTED_SET_NORMALIZED"


class PlanState(StableStringEnum):
    IDLE = "IDLE"
    ANALYZED = "ANALYZED"
    STALE = "STALE"
    APPLYING = "APPLYING"
    APPLIED = "APPLIED"
    VALIDATION_FAILED = "VALIDATION_FAILED"
    RESTORABLE = "RESTORABLE"
    RESTORED = "RESTORED"
    ERROR = "ERROR"


class PlanAvailability(StableStringEnum):
    NONE = "NONE"
    AVAILABLE = "AVAILABLE"
    MISSING = "MISSING"


class WorkflowStage(StableStringEnum):
    NO_CONTEXT = "NO_CONTEXT"
    READY_TO_ANALYZE = "READY_TO_ANALYZE"
    ANALYZING = "ANALYZING"
    READY_TO_APPLY = "READY_TO_APPLY"
    NEEDS_ATTENTION = "NEEDS_ATTENTION"
    BLOCKED = "BLOCKED"
    STALE_SETTINGS = "STALE_SETTINGS"
    STALE_SELECTION = "STALE_SELECTION"
    PLAN_LOST = "PLAN_LOST"
    APPLYING = "APPLYING"
    APPLIED = "APPLIED"
    ROLLBACK_FAILED = "ROLLBACK_FAILED"
    ERROR = "ERROR"


class ActionAvailability(StableStringEnum):
    ENABLED = "ENABLED"
    DISABLED = "DISABLED"


class IssueSeverity(StableStringEnum):
    INFO = "INFO"
    WARNING = "WARNING"
    BLOCKER = "BLOCKER"


class OverrideMode(StableStringEnum):
    NONE = "NONE"
    CURSOR_POSITION = "CURSOR_POSITION"
    REFERENCE_OBJECT = "REFERENCE_OBJECT"
    EXPLICIT_DIRECTION_LENGTH = "EXPLICIT_DIRECTION_LENGTH"
    MESH_VERTEX = "MESH_VERTEX"


OPERATOR_IDS = {
    "analyze": "boneweaver.analyze",
    "check_and_preview": "boneweaver.check_and_preview",
    "apply": "boneweaver.apply",
    "validate": "boneweaver.validate",
    "preview_toggle": "boneweaver.preview_toggle",
    "restore_snapshot": "boneweaver.restore_snapshot",
    "export_report": "boneweaver.export_report",
    "export_conversion": "boneweaver.export_conversion",
    "clear_runtime": "boneweaver.clear_runtime",
    "locate_issue": "boneweaver.locate_issue",
    "load_details": "boneweaver.load_details",
    "inspect_active_hierarchy": "boneweaver.inspect_active_hierarchy",
    "select_inspected_scope": "boneweaver.select_inspected_scope",
    "use_inspected_scope": "boneweaver.use_inspected_scope",
    "set_branch_continuation": "boneweaver.set_branch_continuation",
    "clear_hierarchy_inspection": "boneweaver.clear_hierarchy_inspection",
    "discover_secondary_chains": "boneweaver.discover_secondary_chains",
    "select_discovered_chain": "boneweaver.select_discovered_chain",
    "use_discovered_chains": "boneweaver.use_discovered_chains",
    "clear_semantic_discovery": "boneweaver.clear_semantic_discovery",
    "export_semantic_discovery": "boneweaver.export_semantic_discovery",
    "quick_reorient_auto": "boneweaver.quick_reorient_auto",
    "quick_reorient_restore": "boneweaver.quick_reorient_restore",
}

CANDIDATE_SCORING_PROFILE = (
    ("mesh_support", 0.40),
    ("chain_continuity", 0.25),
    ("cloud_shape_suitability", 0.15),
    ("imported_axis_prior", 0.10),
    ("length_plausibility", 0.10),
)

ERROR_CODES = frozenset(
    {
        "BONEWEAVER_NO_ACTIVE_ARMATURE", "BONEWEAVER_EMPTY_SELECTION", "BONEWEAVER_LINKED_ARMATURE",
        "BONEWEAVER_SHARED_ARMATURE_DATA", "BONEWEAVER_UNSUPPORTED_CONTEXT",
        "BONEWEAVER_NON_INVERTIBLE_TRANSFORM", "BONEWEAVER_NEGATIVE_OBJECT_TRANSFORM",
        "BONEWEAVER_NON_UNIFORM_OBJECT_SCALE", "BONEWEAVER_NON_IDENTITY_POSE",
        "BONEWEAVER_RELATED_ACTION", "BONEWEAVER_RELATED_NLA", "BONEWEAVER_RELATED_DRIVER",
        "BONEWEAVER_RELATED_CONSTRAINT", "BONEWEAVER_BONE_PARENTED_OBJECT",
        "BONEWEAVER_EXTERNAL_CONNECTED_CHILD", "BONEWEAVER_BRANCH_AMBIGUOUS",
        "BONEWEAVER_BRANCH_AUTO_MAIN_SKELETON_FORBIDDEN",
        "BONEWEAVER_BRANCH_AUTO_CONTROL_FORBIDDEN", "BONEWEAVER_BRANCH_AUTO_SOCKET_FORBIDDEN",
        "BONEWEAVER_BRANCH_AUTO_TWIST_FORBIDDEN",
        "BONEWEAVER_BRANCH_AUTO_SECONDARY_SEMANTICS_REQUIRED",
        "BONEWEAVER_COINCIDENT_HELPER", "BONEWEAVER_ZERO_LENGTH_PROPOSAL",
        "BONEWEAVER_NO_ASSOCIATED_MESH", "BONEWEAVER_NO_WEIGHT_GROUP",
        "BONEWEAVER_INSUFFICIENT_WEIGHT_CLOUD", "BONEWEAVER_DISCONNECTED_WEIGHT_ISLANDS",
        "BONEWEAVER_LOW_WEIGHT_CONFIDENCE", "BONEWEAVER_IMPORTED_FORWARD_AXIS_UNAVAILABLE",
        "BONEWEAVER_FORWARD_AXIS_AMBIGUOUS", "BONEWEAVER_TERMINAL_CANDIDATE_AMBIGUOUS",
        "BONEWEAVER_TERMINAL_CANDIDATE_SCORE_TOO_LOW", "BONEWEAVER_VIRTUAL_TIP_INVALID",
        "BONEWEAVER_PHYSICS_GRAPH_INVALID", "BONEWEAVER_GRAPH_PROJECTION_MISMATCH",
        "BONEWEAVER_LONG_SEGMENT_SAMPLING_HINT", "BONEWEAVER_WEIGHT_DIRECTION_CONFLICT",
        "BONEWEAVER_WEIGHT_ISLAND_POLICY_BLOCKED",
        "BONEWEAVER_ENVELOPE_DEFORMATION", "BONEWEAVER_ENVELOPE_MULTIPLY",
        "BONEWEAVER_BBONE_UNSUPPORTED", "BONEWEAVER_AMBIGUOUS_ARMATURE_MODIFIER",
        "BONEWEAVER_TOPOLOGY_MODIFIER_BEFORE_ARMATURE", "BONEWEAVER_STATE_CHANGED_AFTER_ANALYZE",
        "BONEWEAVER_SETTINGS_CHANGED_AFTER_ANALYZE", "BONEWEAVER_WEIGHT_DIGEST_CHANGED",
        "BONEWEAVER_BASE_MESH_CHANGED", "BONEWEAVER_MODIFIER_DIGEST_CHANGED",
        "BONEWEAVER_NEUTRAL_MESH_CHANGED", "BONEWEAVER_NON_TARGET_BONE_CHANGED",
        "BONEWEAVER_ROLL_FALLBACK_USED", "BONEWEAVER_SNAPSHOT_WRITE_FAILED",
        "BONEWEAVER_ROLLBACK_FAILED", "BONEWEAVER_RESTORE_CONFLICT",
        "BONEWEAVER_SCHEMA_VERSION_UNSUPPORTED", "BONEWEAVER_INTERNAL_ERROR",
        "BONEWEAVER_TERMINAL_SAFE_FALLBACK_USED", "BONEWEAVER_TERMINAL_PARENT_UNAVAILABLE",
        "BONEWEAVER_TERMINAL_FALLBACK_INELIGIBLE", "BONEWEAVER_TERMINAL_LENGTH_EVIDENCE_INVALID",
        "BONEWEAVER_BRANCH_MEDIUM_CONFIDENCE", "BONEWEAVER_LEGACY_OVERRIDE_UNSCOPED",
        "BONEWEAVER_UNRECORDED_BONE_MUTATION", "BONEWEAVER_MUTATION_WITHOUT_PROPOSAL",
        "BONEWEAVER_EXPORT_PLAN_MISSING", "BONEWEAVER_EXPORT_PLAN_STALE",
        "BONEWEAVER_EXPORT_APPLY_NOT_SUCCESSFUL", "BONEWEAVER_EXPORT_SNAPSHOT_MISSING",
        "BONEWEAVER_EXPORT_SNAPSHOT_PLAN_MISMATCH", "BONEWEAVER_EXPORT_NO_ACTUAL_MUTATION",
        "BONEWEAVER_EXPORT_POST_VALIDATION_FAILED", "BONEWEAVER_EXPORT_TOPOLOGY_LEDGER_MISSING",
        "BONEWEAVER_EXPORT_TOPOLOGY_LEDGER_INCOMPLETE", "BONEWEAVER_EXPORT_MUTATION_LEDGER_MISMATCH",
        "BONEWEAVER_EXPORT_TIP_HELPER_MISMATCH",
        "BONEWEAVER_MANUAL_OVERRIDE_CONNECTED_TIP_HELPER",
        "BONEWEAVER_EXPORT_UNRESOLVED_BLOCKER", "BONEWEAVER_EXPORT_SOURCE_FILE_MISSING",
        "BONEWEAVER_EXPORT_SOURCE_OVERWRITE_FORBIDDEN", "BONEWEAVER_EXPORT_SOURCE_FILE_CHANGED",
        "BONEWEAVER_REOPEN_VALIDATION_FAILED", "BONEWEAVER_REOPEN_MANIFEST_MISSING",
        "BONEWEAVER_REOPEN_SNAPSHOT_MISSING", "BONEWEAVER_REOPEN_SNAPSHOT_NOT_APPLIED",
        "BONEWEAVER_REOPEN_MUTATION_LEDGER_MISMATCH", "BONEWEAVER_REOPEN_ARMATURE_MISSING",
        "BONEWEAVER_REOPEN_BONE_MISSING", "BONEWEAVER_REOPEN_REST_GEOMETRY_MISMATCH",
        "BONEWEAVER_REOPEN_CONNECT_MISMATCH", "BONEWEAVER_REOPEN_BRANCH_MAIN_PATH_MISMATCH",
        "BONEWEAVER_REOPEN_BRANCH_SIDE_CONNECT_MISMATCH", "BONEWEAVER_REOPEN_LINEAR_CONTINUITY_MISMATCH",
        "BONEWEAVER_REOPEN_PACKED_IMAGE_COUNT_MISMATCH",
        "BONEWEAVER_REOPEN_TIP_HELPER_CLASSIFICATION_MISMATCH",
        "BONEWEAVER_REOPEN_TIP_HELPER_GEOMETRY_MISMATCH",
        "BONEWEAVER_REOPEN_TIP_HELPER_MUTATION_DETECTED",
        "BONEWEAVER_REOPEN_TOPOLOGY_LEDGER_MISMATCH",
        "BONEWEAVER_HIERARCHY_NO_ACTIVE_BONE", "BONEWEAVER_HIERARCHY_INSPECTION_MISSING",
        "BONEWEAVER_HIERARCHY_FILE_CHANGED", "BONEWEAVER_HIERARCHY_ARMATURE_CHANGED",
        "BONEWEAVER_HIERARCHY_BRANCH_INVALID",
        "BONEWEAVER_HIERARCHY_SCOPE_CHANGED_REANALYZE",
        "BONEWEAVER_HIERARCHY_TIP_HELPER_IDENTITY_CHANGED",
        "BONEWEAVER_HIERARCHY_TIP_HELPER_PARENT_REQUIRED",
        "BONEWEAVER_TIP_HELPER_INCLUDE_PROFILE_REQUIRED",
        "BONEWEAVER_TIP_HELPER_INCLUDE_UNSAFE",
        "BONEWEAVER_SEMANTIC_DISCOVERY_MISSING", "BONEWEAVER_SEMANTIC_FILE_CHANGED",
        "BONEWEAVER_SEMANTIC_ARMATURE_CHANGED", "BONEWEAVER_SEMANTIC_CHAIN_INVALID",
        "BONEWEAVER_SEMANTIC_CONFIRMATION_REQUIRED",
        "BONEWEAVER_SEMANTIC_SCOPE_CHANGED_REANALYZE",
        "BONEWEAVER_SEMANTIC_EXPORT_FAILED", "BONEWEAVER_SEMANTIC_RULE_LOAD_FAILED",
        "BONEWEAVER_SCOPE_SOURCE_CONFLICT",
        "BONEWEAVER_QUICK_NO_ACTIVE_ARMATURE",
        "BONEWEAVER_QUICK_LINKED_ARMATURE",
        "BONEWEAVER_QUICK_SHARED_ARMATURE_DATA",
        "BONEWEAVER_QUICK_RELATED_ACTION",
        "BONEWEAVER_QUICK_RELATED_NLA",
        "BONEWEAVER_QUICK_RELATED_DRIVER",
        "BONEWEAVER_QUICK_RELATED_CONSTRAINT",
        "BONEWEAVER_QUICK_BONE_PARENTED_OBJECT",
        "BONEWEAVER_QUICK_BBONE_UNSUPPORTED",
        "BONEWEAVER_QUICK_ENVELOPE_DEFORMATION",
        "BONEWEAVER_QUICK_EXTERNAL_CONNECTED_CHILD",
        "BONEWEAVER_QUICK_ZERO_LENGTH",
        "BONEWEAVER_QUICK_STATE_CHANGED",
        "BONEWEAVER_QUICK_POST_VALIDATION_FAILED",
        "BONEWEAVER_QUICK_RESTORE_CONFLICT",
    }
)
